config/routes.rb
Depot::Application.routes.draw do
  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ronak Online Books Store</title>
    <%= stylesheet_link_tag "scaffold" %>
    <%= stylesheet_link_tag "depot", :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body id="store" >
    <div id="banner" >
      <%#= image_tag("/images/logo.png") %>
      <%= @page_title || "Ronak Book Store" %>
    </div>
    <div id="columns" >
      <div id="side" >
      <% if @cart %>
<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
<%= render @cart %>
<% end %>
<% end %>
        <%= link_to 'Home', store_index_path %><br />
       <br/>
        <br/>
        <%= link_to 'Orders', orders_path %><br />
        <%= link_to 'Products',products_path %><br />
        
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      </div>
      <div id="main" >
         <div id="user_nav" align="right">
<% if user_signed_in? %>
      Signed in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'Register', new_user_registration_path %>
      or <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>